# first stage
FROM python:3.8 as builder
COPY requirements.txt .

# install dependencies
RUN pip install -r requirements.txt

# second unnamed stage
FROM python:3.8-slim
WORKDIR /code

# copy only the dependencies installation from the 1st stage
COPY --from=builder /root/.local/bin /root/.local
COPY . .

# update PATH env var
ENV PATH=/root/.local:$PATH

# command to run on container start
CMD ["python","./server.py"]
