# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-23 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homecopy', models.TextField()),
            ],
        ),
    ]
