# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-16 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0002_imagequeue_newsitemqueue_tickerqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signs.ImageQueue'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='newsitems',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signs.NewsitemQueue'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='tickers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signs.TickerQueue'),
        ),
    ]
