# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-23 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0005_auto_20161222_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imagequeue',
        ),
    ]
