# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-23 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0006_remove_image_imagequeue'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imagequeue',
            field=models.ManyToManyField(to='signs.ImageQueue'),
        ),
    ]
