# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-23 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0007_image_imagequeue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imagequeue',
        ),
        migrations.AddField(
            model_name='imagequeue',
            name='images',
            field=models.ManyToManyField(to='signs.Image'),
        ),
        migrations.RemoveField(
            model_name='newsitemqueue',
            name='newsitems',
        ),
        migrations.AddField(
            model_name='newsitemqueue',
            name='newsitems',
            field=models.ManyToManyField(to='signs.Newsitem'),
        ),
        migrations.RemoveField(
            model_name='tickerqueue',
            name='tickers',
        ),
        migrations.AddField(
            model_name='tickerqueue',
            name='tickers',
            field=models.ManyToManyField(to='signs.Ticker'),
        ),
    ]
