# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-23 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0009_auto_20161222_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsitem',
            old_name='newsText',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='newsitem',
            old_name='newsTitle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='ticker',
            old_name='tickerItem',
            new_name='name',
        ),
    ]
