# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-23 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0010_auto_20161222_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screen',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
